import localFont from "next/font/local";
import { Inter } from "next/font/google";
import { Oxanium } from "next/font/google";

import "./globals.css";
import Footer from "./common/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({
  subsets: ['latin']
});
const oxanium = Oxanium({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oxanium",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={oxanium.variable}>
      <body
        className={`${inter.className} antialiased min-h-screen flex flex-col`}
      >
        <main className="flex-grow bg-gradient-to-b from-[#ffffff] via-[#f5f5f5] to-[#eaeaea]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
